import turtle
from turtle import*
turtle.Screen().bgcolor('#00ffff')
flag=turtle.Pen()
outline=turtle.Pen()
#Drawing flag of my nation using Turtle
#Function to draw flag
def draw_flag():
    flag.shape("turtle")
    flag.penup()
    flag.setpos(-300,-180)
    flag.pendown()
    flag.color("blue")#outline of My country flag is blue
    flag.pensize(5)
    flag.fillcolor('red')#Flag background color is red
    flag.begin_fill()
    flag.lt(90)
    flag.fd(240)
    #creating two traingles
    flag.right(130)
    flag.fd(150)
    flag.right(140)
    flag.fd(100)
    flag.lt(140)
    flag.fd(150)
    flag.right(140)
    flag.fd(120)
    flag.left(90)
    flag.forward(50)
    flag.end_fill()
    flag.penup()
    flag.setpos(-280,-10)
    #creating moon inside flag
    flag.fillcolor('white')
    flag.begin_fill()
    flag.circle(15,180)
    flag.end_fill()
    flag.setpos(-250,-90)
    #creating sun inside flag
    flag.fillcolor('white')
    flag.begin_fill()
    flag.circle(15,360)
    flag.end_fill()
    flag.setpos(0,0)
#border_outline is to create the border of drawing
def border_outline(x,y,z):
    outline.shape("square")
    outline.pensize(5)
    outline.penup()
    outline.setpos(x,y) 
    outline.pendown()
    for i in range(0,4):
        if(i%2==0):
            outline.fd(600+z+z)
            outline.left(90)  
        if(i%2!=0):
            outline.fd(300+z+z)
            outline.left(90)
#writing short form of my country Name Nepal=NPL
def write_name():
    N=turtle.Pen()
    N.color("Red")
    N.pensize(5)
    P=turtle.Pen()
    P.color("blue")
    P.pensize(5)
    L=turtle.Pen()
    L.color("Green")
    L.pensize(5)
    N.shape("triangle")
    N.penup()
    N.setpos(-100,-180) 
    N.pendown()
    N.left(90)
    N.fd(240)
    N.right(160)
    N.fd(256)
    N.left(160)
    N.fd(242)
    P.shape("triangle")
    P.penup()
    P.setpos(20,-180) 
    P.pendown()
    P.left(90)
    P.fd(240)
    for i in range(0,3):
        P.right(90)
        P.fd(100)
    L.shape("triangle")
    L.penup()
    L.setpos(140,60) 
    L.pendown()
    L.right(90)
    L.fd(240)
    L.left(90)
    L.fd(100)
draw_flag()
write_name()
border_outline(-340,-210,0)
border_outline(-360,-230,20)
delay=input("press enter to finish")
